### ISSUE TITLE
.net compiler imports removed

### ISSUE THREAD

**Issue by PhilPJL** [CloudNimble/PackageReferenceUpgrader#4] opened 2017-10-13 13:47 UTC
### Installed product versions
- Visual Studio: 2017 (15.5.0)

### Description
The .net compiler import statements are removed - not sure if an issue or not.

![snip](https://user-images.githubusercontent.com/271656/31549215-6732d496-b025-11e7-84b8-c4af40dd84a0.png)

**Comment by robertmclaws** [comment] 2017-10-13 14:00
This is as designed, the PackageReferences are supposed resolve those automatically. Are you seeing an issue because the imports are missing?

**Comment by PhilPJL** [comment] 2017-10-13 16:22
Roberts, as I said - not sure if an issue or not.  I'll have to check the changes in and kick off a build then see what happens - will do later.

**Comment by robertmclaws** [comment] 2017-10-15 18:32
Yeah, this is by design. The PackageReference system handles .targets in the packages automatically.

I'm closing this one for now, but please feel free to re-open if you notice that it causes an issue I haven't encountered yet.

**Closed as completed by robertmclaws** 2017-10-15 18:32 UTC
Labels: by design
